version: 0.0
os: linux
files:
  - source: /
    destination: /opt
hooks:
  ApplicationStop:
    - location: codedeploy/ApplicationStop.sh
  ApplicationStart:
    - location: codedeploy/ApplicationStart.sh
  ValidateService:
    - location: codedeploy/ValidateService.sh