version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/sbin
file_exists_behavior: OVERWRITE
permissions:
  - object: /usr/local/sbin/deployment
    mode: 755
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: deployment/ApplicationStop.sh
      runas: root
  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      runas: root
  ValidateService:
    - location: deployment/ValidateService.sh
