version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/sbin
hooks:
  ApplicationStop:
    - location: deployment/ApplicationStop.sh
  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      runas: root
  ValidateService:
    - location: deployment/ValidateService.sh
