version: 0.0
os: linux
files:
  - source: /
    destination: /opt
hooks:
  ApplicationStop:
    - location: /opt/deployment/ApplicationStop.sh
  ApplicationStart:
    - location: /opt/deployment/ApplicationStart.sh
      runas: root