version: 0.0
os: linux
files:
  - source: /
    destination: /opt
hooks:
  ApplicationStop:
    - location: deployment/ApplicationStop.sh
  ApplicationStart:
    - location: deployment/ApplicationStart.sh
  ValidateService:
    - location: deployment/ValidateService.sh