version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/sbin
file_exists_behavior: OVERWRITE
permissions:
  - object: /usr/local/sbin/deployment
    mode: 755
    pattern: "**"
    owner: ec2-user
hooks:
  BeforeInstall:
    - location: deployment/ApplicationStop.sh
      runas: root
  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      runas: root
  ValidateService:
    - location: deployment/ValidateService.sh
